### ISSUE TITLE
Unable to run plinkliftover liftover in a remote server. Error: No such command ...

### ISSUE THREAD

**Issue by MrLocuace** [milescsmith/PLINKLiftOver#238]
I installed plinkliftover in a remote server (Python 3.8.5):

pip install -U plinkliftover

I run this command:

plinkliftover liftover chile271samples.snps.2alleles.maf0.01.c1_22.norm.map /project/he/USERS/me/czi/data/liftover/hg19ToHg38.over.chain.gz --prefix chile271.8MM.hg38 --liftoverexecutable /home/me/.local/bin/plinkliftover

I get:

[me@midway3-login4 chile.all]$ plinkliftover liftover chile271samples.snps.2alleles.maf0.01.c1_22.norm.map /project/he/USERS/me/czi/data/liftover/hg19ToHg38.over.chain.gz --prefix chile271.8MM.hg38 --liftoverexecutable /home/me/.local/bin/plinkliftover
Converting MAP file chile271samples.snps.2alleles.maf0.01.c1_22.norm.map file to UCSC BED file chile271samples.snps.2alleles.maf0.01.c1_22.norm.bed...
  [####################################]  100%          
Lifting BED file chile271samples.snps.2alleles.maf0.01.c1_22.norm.bed...
Usage: plinkliftover [OPTIONS] COMMAND [ARGS]...
Try 'plinkliftover --help' for help.

Error: No such command 'chile271samples.snps.2alleles.maf0.01.c1_22.norm.bed'.
Traceback (most recent call last):
  File "/home/me/.local/bin/plinkliftover", line 8, in <module>
    sys.exit(app())
  File "/home/me/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/me/.local/lib/python3.8/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/me/.local/lib/python3.8/site-packages/plinkliftover/__main__.py", line 80, in liftover
    lifted_set, unlifted_set, lb_status = liftBed(
  File "/home/me/.local/lib/python3.8/site-packages/plinkliftover/liftover.py", line 47, in liftBed
    check_output(params.values())
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'dict_values([PosixPath('/home/lucasvicuna82/.local/bin/plinkliftover'), PosixPath('chile271samples.snps.2alleles.maf0.01.c1_22.norm.bed'), '/project/he/USERS/me/czi/data/liftover/hg19ToHg38.over.chain.gz', PosixPath('chile271samples.snps.2alleles.maf0.01.c1_22.norm.map.bed'), 'chile271samples.snps.2alleles.maf0.01.c1_22.norm.map.bed.unlifted'])' returned non-zero exit status 2.

I have tried many different modifications in the script, but none of them work.

Please help

**Comment by MrLocuace** [comment]
Hello,
I did provide the code and the content of the screenshots

**Comment by MrLocuace** [comment]
Could you please provide me an email address to I can share the files privately?
Thank you
